ingress:
    nginx:
        enable: true
        name: orders-ingress-nginx
        domain: orders.sttc.com
        sslredirect: false
        secret: orders.secret
        paths:
            orders: /orders-ms/api/
            ui: /orders-ms/ui/
    istio:
        enable: false
        gatewayName: orders-gateway
        virtualServiceName: orders-vts
        domain:
            http: "*"
            https: orders.sttc.com
            vts: "*"
        secret: orders.secret
        paths:
            orders: /orders-ms/api/
            ui: /orders-ms/ui/
ui:
    name: orders-ui
    version: v1
    replicas: 1
    image:
        repo: luisw19/orders-ui
        tag: 3.0.0
    port: 8080

mongo:
    name: orders-mongo-db
    version: v1
    replicas: 1
    image:
        repo: mongo
    port: 27017

orders:
    name: orders-ms
    version: v1
    replicas: 1
    image:
        repo: luisw19/orders-ms
        tag: 3.0.1
    port: 3000

prodSub:
    name: product-sub-ms
    version: v1
    replicas: 1
    image:
        repo: luisw19/product-sub-ms
        tag: 3.0.0

ordersProd:
    name: orders-prod-ms
    version: v1
    replicas: 1
    image:
        repo: luisw19/orders-prod-ms
        tag: 3.0.0
    port: 4000

env:
    apiHost: https://129.213.126.223:9022
    apiKey: 351801a3-0c02-41c1-b261-d0e5aaa4a0e6
    kafkaBroker: 130.61.35.61:9092
    kafkaRegistry: http://130.61.35.61:8081
    kafkaShoppingCartTopic: idcs-1d61df536acb4e9d929e79a92f3414b5-soaringaddtoshoppingcart
    kafkaOrderTopic: idcs-1d61df536acb4e9d929e79a92f3414b5-soaringordercreated
