ingress:
    nginx:
        enabled: false
        name: orders-ingress-nginx
        domain: orders.sttc.com
        sslredirect: false
        secret: orders.secret
        paths:
            orders: /orders-ms/api/
            ui: /orders-ms/ui/
    istio:
        enabled: false
        gatewayName: orders-gateway
        virtualServiceName: orders-vts
        domain:
            http: "*"
            https: orders.sttc.com
            vts: "*"
        secret: orders.secret
        paths:
            orders: /orders-ms/api/
            ui: /orders-ms/ui/
ui:
    name: orders-ui
    version: v4
    replicas: 1
    image:
        repo: luisw19/orders-ui
        #tag: 3.0.4 #last working version without shipping offers
        tag: 4.0.5
    port: 8080

mongo:
    name: orders-mongo-db
    version: v4
    replicas: 1
    image:
        repo: mongo
    port: 27017

prodSub:
    name: product-sub-ms
    version: v4
    replicas: 1
    image:
        repo: luisw19/product-sub-ms
        #tag: 3.0.1 #last working version without shipping offers
        tag: 4.0.0

orders:
    name: orders-ms
    version: v4
    replicas: 1
    image:
        repo: luisw19/orders-ms
        #tag: 3.0.1 #last working version without shipping offers
        tag: 4.0.1
    port: 3000

ordersProd:
    name: orders-prod-ms
    version: v4
    replicas: 1
    image:
        repo: luisw19/orders-prod-ms
        #tag: 3.0.1 #last working version without shipping offers
        tag: 4.0.0
    port: 4000

env:
    apiHost: http://130.61.20.66:8011
    apiKey: 351801a3-0c02-41c1-b261-d0e5aaa4a0e6
    kafkaBroker: 18.184.145.38:9092
    kafkaRegistry: http://18.184.145.38:18081
    kafkaShoppingCartTopic: soaring-add-to-shopping-cart
    kafkaOrderTopic: soaring-ordercreated
