version: '2'
services:
  orders-ui:
      #Image
      image: luisw19/orders-ui:1.0.5
      #Uncomment "build" if you wish to build from source code, otherwise it'll pull from registry
      build: ./ui
      environment:
        API_HOST: 'https://oc-129-156-113-240.compute.oraclecloud.com:9022'
        API_KEY: '351801a3-0c02-41c1-b261-d0e5aaa4a0e6'
      ports:
        - "8080:8080"
      command: bash container-entrypoint.sh

  product-sub-ms:
      #Image
      #image: localhost/product-sub-ms:0.1.1
      image: luisw19/product-sub-ms:2.0.0
      #Uncomment "build" if you wish to build from source code, otherwise it'll pull from registry
      build: ./product-subscriber-ms
      environment:
        KAFKA_BROKER: '129.156.113.171:6667'
        KAFKA_REGISTRY: 'http://129.156.113.125:8081'
        KAFKA_SHOPPINGCART_TOPIC: 'idcs-1d61df536acb4e9d929e79a92f3414b5-soaringaddtoshoppingcart'
        ORDERSAPI_HOST: 'orders-ms'
        ORDERSAPI_PORT: 3000
      command: node product-subscriber-ms.js
      links:
        - orders-ms

  orders-ms:
      #Image
      #image: localhost:3000/orders-ms:0.1.0
      image: luisw19/orders-ms:2.0.0
      #Uncomment "build" if you wish to build from source code, otherwise it'll pull from registry
      build: ./orders-ms
      environment:
        APP_PORT: 3000
        EVENTAPI_HOST: 'orders-prod-ms'
        EVENTAPI_PORT: 4000
      depends_on:
        - orders-mongo-db
      ports:
        - "3000:3000"
      command: npm start
      links:
        - orders-mongo-db
        - orders-prod-ms

  orders-prod-ms:
      #Image
      #image: localhost/product-sub-ms:0.1.1
      image: luisw19/orders-prod-ms:2.0.0
      #Uncomment "build" if you wish to build from source code, otherwise it'll pull from registry
      build: ./orders-producer-ms
      environment:
        APP_PORT: 4000
        KAFKA_BROKER: '129.156.113.171:6667'
        KAFKA_REGISTRY: 'http://129.156.113.125:8081'
        KAFKA_ORDER_TOPIC: 'idcs-1d61df536acb4e9d929e79a92f3414b5-soaringordercreated'
      ports:
            - "4000:4000"
      command: npm start

  orders-mongo-db:
      image: mongo
