# APP DEPLOYMENT

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: orders-ui
  name: orders-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      run: orders-ui
  template:
    metadata:
      labels:
        run: orders-ui
    spec:
      containers:
      - args:
        - bash
        - container-entrypoint.sh
        env:
        - name: API_HOST
          value: https://oc-129-156-113-240.compute.oraclecloud.com:9022
        - name: API_KEY
          value: 351801a3-0c02-41c1-b261-d0e5aaa4a0e6
        image: luisw19/orders-ui:2.0.8
        name: orders-ui
        ports:
        - containerPort: 8080
      restartPolicy: Always

---

# APP SERVICE

apiVersion: v1
kind: Service
metadata:
  labels:
    run: orders-ui
  name: orders-ui
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: orders-ui
  type: NodePort
