#include the body if ingress.nginx.enable exists and is set to true
{{ if eq .Values.ingress.nginx.enable true }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Values.ingress.nginx.name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/add-base-url: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: '{{ .Values.ingress.nginx.sslredirect }}'
    #nginx.ingress.kubernetes.io/ssl-redirect: 'false'
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.nginx.domain }}
    secretName: {{ .Values.ingress.nginx.secret }}
    #secretName: orders-secret
  rules:
  - host: {{ .Values.ingress.nginx.domain }}
    http:
      paths:
      - path: {{ .Values.ingress.nginx.paths.orders }}?(.*)
      #- path: /orders-ms/api/?(.*)
        backend:
          serviceName: {{ .Release.Name }}-{{ .Values.orders.name }}
          servicePort: {{ .Values.orders.port }}
      - path: {{ .Values.ingress.nginx.paths.ui }}?(.*)
      #- path: /orders-ms/ui/?(.*)
        backend:
          serviceName: {{ .Release.Name }}-{{ .Values.ui.name }}
          servicePort: {{ .Values.ui.port }}
{{ end }}
